# Site settings
title:          "ChuheZhang's Tech Blog"  
description:    "A personal blog about technology and programming."  
baseurl:        ""  
url:            "https://ChuheZhang.github.io"  

# Google Analytics
# google_analytics: UA-XXXXXXXX-X  

# Author
author:
  name:         "Chuhe Zhang"  
  url:          https://www.yourwebsite.com  
  # email:        your-email@example.com  

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji # Uncomment this to allow emoji in your posts

# Permalinks
permalink:      /:year-:month-:day/:title  
paginate:       5  
# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]  

# Disqus (Set to your Disqus ID)
# disqus:         jekyll-tale  
